name: ProgressionMMO
author: Lukas Fend
version: 0.1
main: ninja.lukasfend.ProgressionMMO.ProgressionMMO
api-version: 1.17
description: An all-in-one MMO plugin
depend: [HolographicDisplays]
commands:
  pmdev:
    usage: /<command> [player]
    description: Development command
    permission: progressionmmo.devcommand
    aliases: [pmxp]
  pmlevels:
    usage: /<command> [player]
    description: Shows the levels and xp of a player
    aliases: [pmxp]