name: ProgressionMMO
version: '${project.version}'
main: ninja.lukasfend.ProgressionMMO.ProgressionMMO
author: Lukas Fend
api-version: 1.18
description: An all-in-one MMO plugin for Minecraft!
website: lukasfend.ninja
depend: [HolographicDisplays]
commands:
  pmdev:
    usage: Usage /<command> [player]
    description: Development command
    permission: progressionmmo.devcommand
  pmskill:
    usage: Usage /<command> <agility|archery|armorsmithing|attack|defense|farming|fishing|health|herblore|mining|slayer|sorcery|strength|summoning|thieving|weaponsmithing>
    description: Shows extended information about a skill and your current progress
  pmlevels:
    usage: Usage /<command> [player]
    description: Shows the levels and xp of a player
    aliases: [pmxp]
  pmguild:
    usage: Usage /<command> <help>
    description: Command for handling guilds
    aliases: [guild]